language: php
php:
  - 5.4
  - 5.5
  - 5.6

before_script:
  - curl -s https://getcomposer.org/installer|php
  - php composer.phar install --dev --no-interaction

script:
  - php vendor/bin/phploc src
  - php vendor/bin/phpmd src text codesize,unusedcode,controversial,naming,design,cleancode
  - php vendor/bin/phpcs --standard=PSR1,PSR2 src
  - php vendor/bin/codecept run --coverage --coverage-xml --coverage-html
#after_script:
#  - php vendor/bin/coveralls -v