<?php

namespace Apicycle\Common\Exception\Stream;

use Apicycle\Common\Exception\InvalidArgumentTypeException;
use Apicycle\Common\Utility\VariableTypeValidator;
use Exception;

/**
 * Designed to be thrown when invalid seek type is supplied.
 *
 * @codeCoverageIgnore
 *
 * @version 0.1.0
 * @since   0.1.0
 * @package Apicycle\Common\Exception\Stream
 * @author  Etki <etki@etki.name>
 */
class InvalidSeekTypeException extends InvalidArgumentTypeException
{
    /**
     * Initializer.
     *
     * @param string         $argumentName  Name of the argument.
     * @param mixed          $argumentValue Erroneous argument
     * @param string|null    $message       Exception message. Will be
     *                                      autogenerated, if omitted
     * @param Exception|null $previous      Previous exception (if any).
     *
     * @return self
     * @since 0.1.0
     */
    public function __construct(
        $argumentName,
        $argumentValue,
        $message = null,
        Exception $previous = null
    ) {
        if (!$message) {
            $message = 'Stream seek type has been specified with invalid ' .
                'value, `SEEK_SET`, `SEEK_CUR` or `SEEK_END` should be used';
        }
        parent::__construct(
            $argumentName,
            $argumentValue,
            gettype(SEEK_SET),
            $message,
            $previous
        );
    }

    /**
     * Generates exception message.
     *
     * @param mixed $invalidValue Erroneous seek type value.
     *
     * @return string Composed message.
     * @since 0.1.0
     */
    protected function composeMessage($invalidValue)
    {
        if (VariableTypeValidator::isCastableToString($invalidValue)) {
            return sprintf(
                'Stream seek type has been specified with invalid value ' .
                '`%s`, `SEEK_SET`, `SEEK_CUR` or `SEEK_END` should be used',
                (string) $invalidValue
            );
        }
        return sprintf(
            'Stream seek type has been specified with invalid value of type ' .
            '`%s`, `SEEK_SET`, `SEEK_CUR` or `SEEK_END` should be used',
            gettype($invalidValue)
        );
    }
}
