<?php

namespace Apicycle\Common\Exception\Stream;

use Exception;

/**
 * Designed to be thrown whenever unreadable stream is hit.
 *
 * @version 0.1.0
 * @since   0.1.0
 * @package Apicycle\Common\Exception\Stream
 * @author  Etki <etki@etki.name>
 */
class UnreadableStreamException extends StreamException
{
    /**
     * Initializer.
     *
     * @param string|null $message  Exception message, will be autogenerated if
     *                              omitted.
     * @param Exception   $previous Previous exception (if any).
     *
     * @codeCoverageIgnore
     *
     * @return self
     * @since 0.1.0
     */
    public function __construct($message = null, Exception $previous = null)
    {
        $message = $message ? $message : 'Couldn\'t read from stream';
        parent::__construct($message, 0, $previous);
    }
}
